// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using olsoftware.Models;

namespace olsoftware.Migrations
{
    [DbContext(typeof(OlSoftwareDbContext))]
    [Migration("20200918191205_OlSoftwareDbContext")]
    partial class OlSoftwareDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("olsoftware.Models.AllModelsParams.ClientesParams", b =>
                {
                    b.Property<long>("idcard")
                        .HasColumnType("bigint");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("phone")
                        .HasColumnType("bigint");

                    b.HasKey("idcard");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("olsoftware.Models.AllModelsParams.ProyectosParams", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nhours")
                        .HasColumnType("int");

                    b.Property<DateTime>("dend")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dinit")
                        .HasColumnType("datetime2");

                    b.Property<long>("iduser")
                        .HasColumnType("bigint");

                    b.Property<string>("lenguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("state")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("iduser");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("olsoftware.Models.AllModelsParams.ProyectosParams", b =>
                {
                    b.HasOne("olsoftware.Models.AllModelsParams.ClientesParams", "ClientesParams")
                        .WithMany("PPAR")
                        .HasForeignKey("iduser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
